


= How do I get involved?

== Getting Started

1. Join the Element Fedora Design https://matrix.to/\&#35;/\&#35;design:fedoraproject.org[group chat].
2. Introduce yourself to the group; talk about your art/design experience and interests so we'll know what kinds of design tasks you might be interested in helping out with.
3. Sign up for a https://docs.fedoraproject.org/en-US/fedora-accounts/user[Fedora Account], you'll need it later!
4. Complete the https://docs.fedoraproject.org/en-US/legal/fpca[Fedora Project Contributor Agreement] (FPCA) through the https://docs.fedoraproject.org/en-US/fedora-accounts/user[Account System]. This will ensure that the contributions you make are properly licensed!
5. Complete a small task to join the team. To find something to work on, you can do any of the following:
\&#42; Claim and complete a design ticket at the https://gitlab.com/fedora/design/team/requests/-/issues[Fedora Design Issue Request queue].
\&#42; Look at the https://gitlab.com/groups/fedora/design/team/-/issues[Fedora Design issues], and see if any are flagged for newbies!
\&#42; Ask the group in Element if there are any tickets that need attention.
Note: We definitely recommend for folks starting out with our team to look for tasks that are not icon-related. Icon designs pose additional burdens and challenges that we don't want you to have to deal with just starting out! The same applies to logos.
6. Once you've completed an initial draft of your design task, comment on the ticket, and pop the link or artwork in the https://matrix.to/\&#35;/\&#35;design:fedoraproject.org[Element design group chat] for feedback and approval.
7. Once your design is approved, send a message to the design team in Element requesting an invite to the design-team group. Provide your Fedora Account username so we can add you in.

After you have completed these steps, you can begin contributing to a project as a full member of the design team. Questions and suggestions may be asked within the ticket as well as the Fedora Design group chat on Element.

== Join our meetings!

Video meetings will be held every \&#42;Monday at 14:30 UTC\&#42; on https://meet.jit.si/FedoraDesign[\&#42;Jitsi\&#42;]. Please note that audio and video is not required to join the meeting - you can always use the chat for input if that is more comfortable for you.

Check the https://calendar.fedoraproject.org/design[Design Calendar] for updated meeting times. Meeting logs can be found at https://meetbot.fedoraproject.org/[meetbot.fedoraproject.org].

== Chat with us!

Design team members are present on the https://matrix.to/\&#35;/\&#35;design:fedoraproject.org[\&#42;\&#35;design:fedoraproject.org\&#42; Matrix room] on https://chat.fedoraproject.org/[chat.fedoraproject.org].
Feel free to reach us here!








= Resources

Dedicated page to help you find assets, tutorials, and recommended software to support your work and contributions.

== Assets

\&#42; https://docs.fedoraproject.org/en-US/project/brand/\&#35;_the_fedora_logo[\&#42;Fedora Logo\&#42;] - Fedora logo information, including usage guidelines
\&#42; https://docs.fedoraproject.org/en-US/project/_attachments/brand-book-revised-2024.pdf[\&#42;Fedora Brand Book\&#42;] - Brand guidelines booklet in PDF format
\&#42; https://gitlab.com/fedora/design/team/event-kit/[\&#42;Event Kit\&#42;] - Design assets related to Fedora events (banners, tablecloth, etc.)
\&#42; https://gitlab.com/fedora/design/team/event-kit/-/tree/main/Stickers[\&#42;Stickers\&#42;] - Print ready sticker files

== Tutorials
\&#42; https://gitlab.com/fedora/design/team/tutorials/inkscape-automation[\&#42;Inkscape Automation\&#42;] - Tutorial for how to use Inkscape to automate the production of SVG, PNG, EPS, PS, or PDF graphics using a template file and CSV data input.

== Open-Source Design Software

\&#42; https://penpot.app/[\&#42;Penpot\&#42;] - web-based design and prototyping platform.

\&#42; https://inkscape.org/[\&#42;Inkscape\&#42;] - vector graphics editor
\&#42;\&#42; https://opensource.com/sites/default/files/gated-content/cheat_sheet_inkscape.pdf[Inkscape cheat sheet]

\&#42; https://www.blender.org/[\&#42;Blender\&#42;] - 3D computer graphics software
\&#42;\&#42; https://opensource.com/sites/default/files/gated-content/cheat_sheet_blender_v2.pdf[Blender cheat sheet]

\&#42; https://krita.org/en/[\&#42;Krita\&#42;] - digital painting application
\&#42;\&#42; https://opensource.com/article/21/12/krita-digital-paint[Open source digital painting with Krita]

\&#42; https://www.gimp.org/[\&#42;GIMP\&#42;] - image editor
\&#42;\&#42; https://www.gimp.org/[GIMP cheat sheet]

\&#42; https://kdenlive.org/en/[\&#42;Kdenlive\&#42;] - video editor
\&#42;\&#42; https://opensource.com/sites/default/files/gated-content/osdc_cheatsheet-kdenlive-2021.12.3.pdf[Kdenlive cheat sheet]





= Need Design Help?

== Filing an issue
You can file an https://gitlab.com/fedora/design/team/requests/-/issues/[issue] to:

\&#42; Request new design work
\&#42; Tell us if something's wrong with an existing design
\&#42; Make a suggestion for a future design

== Now what?

Because this is mainly a volunteer-staffed team, we don't guarantee to handle all tickets. If you think a ticket needs attention and would like to work on it, but someone else took ownership of the ticket: try to contact the owner and see if they are working on it. If you don't hear from them within a week you can probably take the ticket over. If you have a filed a ticket and have not heard from anyone, please feel free to https://matrix.to/\&#35;/\&#35;design:fedoraproject.org[join our chat] for attention / guidance / support.



