= Fedora Mindshare
:page-layout: without_menu

Mindshare Teams are focused on helping our community grow both the number of users and contributors. The teams in Mindshare are each focused on a different aspect of this goal.

xref:mindshare-committee:ROOT:index.adoc[\&#42;\&#42;Fedora Mindshare Committee\&#42;\&#42;] — The Mindshare Committee fosters communication amongst the Mindshare teams and helps facilitate Council strategy.

== Mindshare Teams

// Include individual team entries as follows:
//  include::COMPONENT:MODULE:partial$FILENAME.adoc[]
//  include::partial$team_render.adoc[]
//
// Or if it's a local file:
//  include::partial$FILENAME.adoc[]
//  include::partial$team_render.adoc[]


// Example 1: A team entry using data stored in a different space

// The Template Team


// Example 2: A team entry using data stored in this repository (using the template)

// The Template Team



// Old entries:
\&#42; xref:commops:ROOT:index.adoc[\&#42;\&#42;Fedora Community Operations (CommOps)\&#42;\&#42;] — Community Operations (CommOps) provides tools, resources, and utilities for different sub-projects of Fedora to improve effective communication.

\&#42; xref:fedora-docs:ROOT:index.adoc[\&#42;\&#42;Fedora Documentation (Docs)\&#42;\&#42;] — The group behind this very documentation site. Includes contributors' guidelines to Fedora Docs

\&#42; xref:badges:ROOT:index.adoc[\&#42;\&#42;Fedora Badges\&#42;\&#42;] — The group behind Fedora Badges — a fun website built to recognize contributors to the Fedora Project, help new and existing Fedora contributors find different ways to get involved, and encourage the improvement of Fedora's infrastructure.

\&#42; xref:fedora-magazine:ROOT:index.adoc[\&#42;\&#42;Fedora Magazine\&#42;\&#42;] — Guidelines around contributing to the Fedora Magazine.

\&#42; xref:websites:ROOT:index.adoc[\&#42;\&#42;Fedora Websites\&#42;\&#42;] - Documentation covering maintenance and expansion of Fedora Project websites.

\&#42; xref:fedora-join:ROOT:index.adoc[\&#42;\&#42;Fedora Join SIG\&#42;\&#42;] - The Fedora Join SIG aims to set up and maintain channels that let prospective contributors engage with the community.

\&#42; xref:ask-fedora-sops:ROOT:index.adoc[\&#42;\&#42;Ask Fedora SOPs\&#42;\&#42;] - Standard operating procedures for the link:https://ask.fedoraproject.org/[Ask Fedora forums].

\&#42; xref:localization:ROOT:index.adoc[\&#42;\&#42;Fedora Localization Project\&#42;\&#42;] - The Fedora Localization Project.

\&#42; xref:docs-l10n:ROOT:index.adoc[\&#42;\&#42;Fedora Docs Localization Stats\&#42;\&#42;] - Statistics about the Fedora documentation localization progress.
// TEMPLATE

// This is a data store of information about a Fedora team.

// File like this would be stored either in the team's docs
// git repository, or if they don't have any (maybe they live on a wiki).
// then it can be stored in the council-docs repo next to the template.

// Team name:

// Team summary:

// Team page URL:

// Team activity status.
// Choose from: Active, Inactive

// Preferred Asynch communication channel (mailing list, discussion.fp.o, none, etc)

// Preferred Synch (Matrix room, none, etc.)

// Issue tracker

// Meetings

// Any other information?
\&#42; https://docs.fedoraproject.org/en-US/council/[\&#42;\&#42;Team Name\&#42;\&#42;] — We serve as a template.
