= Welcome!

This document outlines the important activities you can get involved in to help with https://fedoraproject.org/wiki/QA[Fedora Quality^]
and is meant to guide you through the Quality ecosystem.
It's easy to get involved and we love to welcome people to the group!
The first thing you probably want to do is get plugged in to all the right sources of information for Fedora Quality.

There are six steps you can take to get up to speed with Quality efforts (in rough order of precedence):


\&#42; Create a https://docs.fedoraproject.org/en-US/fedora-accounts[Fedora account^]
\&#42; Subscribe to the https://lists.fedoraproject.org/archives/list/test@lists.fedoraproject.org/[test^] mailing list
\&#42; https://fedoraproject.org/wiki/QA/Join\&#35;self-introduction[Introduce yourself^] to the team!
\&#42; Create a https://bugzilla.redhat.com/createaccount.cgi[Bugzilla Account^]
\&#42; Join our link:pass:[https://chat.fedoraproject.org/\&#35;/room/\&#35;quality:fedoraproject.org][\&amp;\&#35;35;quality:fedoraproject.org^] Matrix room through https://chat.fedoraproject.org/[Fedora Chat^] (or link:https://matrix.to/\&#35;/\&#35;quality:fedoraproject.org[other clients^])
\&#42; Subscribe to the https://discussion.fedoraproject.org/tag/quality-team[quality-team^] tag at https://discussion.fedoraproject.org/[Fedora Discussion^]
\&#42; https://fedoraproject.org/wiki/QA/Join\&#35;onboarding-call[Attend the onboarding call^]

== What are you looking to do?

Whether you are looking to test a https://fedoraproject.org/wiki/Releases[stable release^], a new package from https://fedoraproject.org/wiki/QA:Updates_Testing[updates-testing^], a https://fedoraproject.org/wiki/Releases/Branched[Branched^] https://fedoraproject.org/get-prerelease[pre-release^], or the leading edge https://fedoraproject.org/wiki/Releases/Rawhide[Rawhide^], QA has a way for you to contribute and get involved! We need people who like to push all the buttons, use all the command line options, verify all the documentation, review things for usability, and suggest future features - especially for anything that's undergone major https://fedoraproject.org/wiki/Changes/Policy[change^] in a https://fedoraproject.org/wiki/Changes[recent or pending^] release.


=== If you want to:

\&#42; Work on an upcoming stable release
- https://fedoraproject.org/wiki/QA/Join\&#35;release-validation[Release Validation Testing^]
- https://fedoraproject.org/wiki/QA:Updates_Testing\&#35;What_to_test.2C_testing.2C_and_reporting_results[Updates Testing^]

\&#42; Work on testing new package updates
- https://fedoraproject.org/wiki/QA:Updates_Testing\&#35;What_to_test.2C_testing.2C_and_reporting_results[Updates Testing^]
- https://fedoraproject.org/wiki/Fedora_Easy_Karma[Fedora Easy Karma^]

\&#42; I want to do something else!
- https://fedoraproject.org/wiki/QA/Join\&#35;test-days[Join a Test Day^]
- https://fedoraproject.org/wiki/QA/Join\&#35;create-testcases[Create Test Cases^]
- https://fedoraproject.org/wiki/QA/Join\&#35;develop-tools[Develop Tools^]
- https://fedoraproject.org/wiki/QA/Join\&#35;triage[Triage Bugs^]

For all of those tasks, it would be good to have some familiarity with our Bugzilla instance. A lot of contribution to Fedora Quality comes through bug reports. All you need is a http://bugzilla.redhat.com/[Bugzilla^] account: https://bugzilla.redhat.com/createaccount.cgi[create your account^]. Please make sure that the email addresses for your Fedora account and the Bugzilla account are the same. Our https://fedoraproject.org/wiki/BugsAndFeatureRequests[bug reporting practices^] provide some good background for filing bugs. If you want to discuss the bugs before reporting, QA members can be found on https://fedoraproject.org/wiki/QA\&#35;Communicate[several channels^]. Experienced Quality members are more than happy to act as mentors for new members to help them get started.
There is no requirement of programming knowledge. However, being familiar with Fedora and Linux in general will be extremely useful.

== More information

If you haven't found here what you were looking for, try to visit our https://fedoraproject.org/wiki/QA[Fedora Quality wiki page] to see more information about our team and activities.



