= What we do

Some of the things we do in pursuit of these goals are:

\&#42; Design and development work to integrate upstream components
\&#42; Testing upcoming releases and features
\&#42; Seeking out and engaging contributors from outside the group
\&#42; Coordinating and organising testing initiatives
\&#42; Tracking and resolving workstation issues
\&#42; Deciding which packages are to be included, including which apps are pre-installed
\&#42; Making the final call on major technical changes
\&#42; Ensuring that Fedora processes are adhered to for Workstation, including change and release processes
\&#42; Maintaining the Workstation web pages
\&#42; Facilitating technical discussions
\&#42; Reviewing and critiquing technical plans
\&#42; Publicising the changes in each Workstation release
\&#42; Communicating Workstation changes to other Fedora teams


= Governance

Governance rules for the Fedora Workstation Working Group, an independent subcommittee of FESCo.

== Membership

Members of the Working Group are chosen by the Working Group as needed to maintain a reasonably-sized working group. The Working Group may fill a seat by selecting a candidate and approving by majority of the Working Group membership. Eligible candidates must be in the FPCA+1 group. The Working Group is encouraged to seek out candidates that have been showing persistent and high-quality contribution to Workstation technology or direction.

xref:members.adoc[See current members list.]

== Meetings

The Working Group meets on a regular basis. A quorum, comprised of a majority of the Working Group, is required to conduct business and make binding decisions at meetings.

The Working Group will keep records of discussions, meetings, and votes, and will make these records public to the Fedora community. The Working Group shall generally be open to public observation. However, the Working Group may meet in private when necessary to discuss for sensitive issues, such as legal issues, provided that such private meetings are rare and that the public record indicates that a private meeting occurred and the general topic of the private discussion.

== Making decisions

The Working Group may make binding decisions on any matters affecting the Fedora Workstation product, including any software contained in the product.

The Working Group generally operates by consensus. Formal votes are not required to resolve issues except when disagreement exists. When Working Group members wish to hold a vote, voting may occur either using an online platform accessible to the Fedora community, or during meetings of the Working Group. Working group members can vote +1 to approve, -1 to disagree, or 0 to abstain; a majority vote is necessary for a measure to pass, with abstain votes not being included in the count.

Working Group decisions may be overruled by FESCo.

== Changing these rules

This document was originally approved by consensus of the initial Working Group members and by FESCo. Future substantive changes may be approved by majority vote and sent to FESCo for acceptance.



= Members

The current members of the Workstation Working Group are:

\&#42; Michael Catanzaro (mcatanzaro)
\&#42; Matthias Clasen (mclasen)
\&#42; Allan Day (aday)
\&#42; Neal Gompa (King_InuYasha, Son_Goku)
\&#42; Nieves Montero (nmontero)
\&#42; Chris Murphy (chrismurphy)
\&#42; Jens Petersen (petersen)
\&#42; Tomáš Popela (tpopela)
\&#42; Michel Lind (salimma)

Previous members include:

\&#42; Kalev Lember (kalev)
\&#42; Owen Taylor (otaylor)
\&#42; Langdon White (langdon)
\&#42; Rex Dieter (rdieter)
\&#42; Paul Frields (stickster)
\&#42; Josh Boyer (jwboyer)
\&#42; Christian Schaller (cschalle)

See xref:governance.adoc[governance] to see how official members are appointed.



= Fedora Workstation PRD

\&#42;May 2022\&#42;

This document provides an overview of the goals and objectives of Fedora Workstation. It is intended to allow people to understand the role of Fedora Workstation and how it is likely to develop in future.

The Fedora Workstation PRD is primarily intended for other Fedora Project teams, contributors and stakeholders, so they can better understand Workstation’s role, goals and current priorities.

== Fedora Workstation Vision

Fedora Workstation envisions an open world where developers and creators can easily make new and exciting things with accessible digital platforms.

== Fedora Workstation Mission

Our mission is to continuously advance Fedora Workstation: to make it an ever more capable and powerful operating system for laptops and desktops, and to continually narrow the gap between it and the needs of its users. We aim to continually increase Workstation's capacity to help developers and creators, and to grow the Workstation user and contributor community.

== The Workstation Market

This section describes the audience for Fedora Workstation, our main pitch for that audience, and our main routes to market.

=== Market opportunity

Laptop and desktop devices are at the heart of many creative areas, including software, multimedia, engineering, science, and design. In all these fields, a desktop computer is an essential tool. As such, the critical role of the desktop is firmly established in the market.

The desktop market also has important effects which are felt more widely. Desktops can help to popularize the technologies and ecosystems with which they are associated, and they can be a vehicle for communicating values, principles and practices.

Finally, desktop computers are an important gateway for people who are starting out in their personal journeys in computing, and are a powerful educational and learning tool. Many people remember the first time they installed a Linux operating system as a key moment in their lives. Fedora Workstation wants to be part of that experience, and to make it as good as it possibly can be.

==== A desktop for developers and creators

Workstation's historical focus has been on developer use cases. In practical terms, this translates to:

\&#42; Availability of high quality developer tools, frameworks and platforms.
\&#42; Fantastic command line experience.
\&#42; Prioritization of desktop features which are particularly relevant to developers, including multi-monitor, VPN, and remote desktop.
\&#42; A desktop experience which caters to developers, with features like keyboard-based app launching, window snapping, and a focus on distraction free computing.
\&#42; Support for developer class hardware.
\&#42; A high level of reliability and stability.

However, it should be stressed that developers also require other more basic desktop features and product qualities. Our focus on developers therefore does not compromise our goal to create a polished and user friendly system that appeals to a wide general audience. Many changes and improvements we implement for developers are equally beneficial to other user segments.

Most recently, we have expanded our goals to include other types of digital content creation, in addition to software developers. This expansion of the link:https://fedoraproject.org/wiki/Workstation/Workstation_PRD[initial Fedora Workstation goals] reflects our success in the developer space, and a desire to have broader aspirations.)

==== Use cases

Broad user types that we are interested in include:

\&#42; Undergraduate and postgraduate students
\&#42; Independent developers and content creators
\&#42; Developers working in both large and small organizations

Activities that we are focused on supporting include:

\&#42; Student coursework for CS programs
\&#42; Full stack software development
\&#42; Game development — and playing games!
\&#42; DevOps and systems administration
\&#42; Podcasting and video streaming

=== Why use Fedora Workstation

First and foremost, Fedora Workstation fulfills the most important, basic requirements that people have for a modern desktop operating system:

\&#42; can be relied upon to be usable whenever you need it, without bugs or software updates getting in your way
\&#42; a large collection of applications and other software available to install
\&#42; easy to use and learn, from the very first use or install, through to learning more advanced tasks
\&#42; support for a wide range of high-quality hardware
\&#42; fantastic user experience

Additionally, it has special qualities which are unique to Fedora:

\&#42; provides access to the latest and best open source software, including new cutting-edge features and technologies
\&#42; a welcoming and supportive user community
\&#42; part of the wider Fedora and Red Hat ecosystem
\&#42; developed in the open, in collaboration with upstream projects and communities, following the open source way

=== Go to market

Since our goal is to increase the number of people using Fedora Workstation, it is critical to ensure direct and effective routes to our target audiences. There are three primary routes to market.

==== 1. Self-installation

Self-installation has been and continues to be our primary route to market. Here, the user installs and manages the system themselves.

Some requirements here:

\&#42; Attractive landing site and download page
\&#42; Create install media from a variety of operating systems (via Fedora Media Writer)
\&#42; Live media for testing and demos
\&#42; Install alongside a pre existing OS (primarily Windows)
\&#42; Easy access to help when questions arise

==== 2. Preinstalled OS

Here, the operating system is installed by the hardware manufacturer prior to it being shipped to the user. The preinstallation route to market has been a significant focus for Workstation, that has delivered results through our partnership with Lenovo.

Requirements for manufacturer preinstallation include:

\&#42; Supporting the hardware that Fedora is preinstalled on (to be delivered in partnership with key hardware vendors)
\&#42; Initial system setup should be compatible with OEM installation scenarios
\&#42; Firmware updates for hardware shipped with Fedora

==== 3. Managed deployments

In a managed deployment, the route to market is through organizations which choose to widely deploy and support Fedora. The OS is installed by an administrator, and aspects of the machine are monitored and administered by the organization.

Managed deployments are less developed than Workstation’s other routes to market and this route poses some challenges. However, it remains an important area that we continue to investigate.

Relevant features include:

\&#42; Initial system setup
\&#42; Enterprise login
\&#42; Remote auditing
\&#42; Remote configuration and management
\&#42; System customization for managed cases (for example, customized initial setup and Software categories)

== Fedora Workstation Objectives

This objectives section covers our operational activities in more detail, in pursuit of the broader ambitions described above.

In operational terms, Fedora Workstation’s main goals are to:

\&#42; Be a great developer workstation
\&#42; Be a great general-purpose OS targeting laptops and desktops
\&#42; Work well for content creation (podcasts, video streaming, etc)

Fedora Workstation has had a period of success and has been recognised for delivering a high-quality desktop with new and exciting features. As we move forward, we aim to continue on this upward trajectory by continuing to ensure quality and reliability, while pursuing technology and UX improvements.

Particular areas of interest include:

\&#42; Developer focused features
\&#42; Growing the Fedora contributor community
\&#42; Features and capabilities for content creation, such as podcasting and video streaming
\&#42; Supporting managed Fedora Workstation deployments
\&#42; Filling in outstanding missing pieces around hardware support, multimedia support, security features
\&#42; Increasing the number of apps that are available to install out of the box
\&#42; Enhanced marketing and mindshare

=== Functional requirements

The following describes the features and product attributes that we believe are most important to Fedora Workstation’s success.

==== Quality releases

We continually work to ensure that the core product offered is of the highest quality possible. This includes keeping the core test matrix as small as possible, using a high degree of testing automation, and collaborating with upstream projects to increase general test coverage of core modules. We work closely with Fedora QE and Release Engineering to ensure that Workstation releases are of consistently high quality.

==== Robust upgrades

Because of the fast refreshes and relatively short life cycle of Fedora Linux releases, we need upgrades to be pain-free. Users should approach them without fear.

Upgrading the system multiple times through the upgrade process should give a result that is the same as an original install of Fedora Workstation. Upgrade should be a safe process that never leaves the system needing manual intervention.

If there are any problems with an upgrade or an upgrade breaks a configuration script, we want to offer an easy way for users to roll back such upgrades and changes.

==== Broad application availability

Our goal is to provide easy access to common best in class desktop applications, including:

\&#42; general desktop apps for web browsing, music, cloud drives and chat
\&#42; development tools, including IDEs, compilers, debugging and testing tools
\&#42; content creation tools, such as multimedia recording and process, and image and video editing

Flatpak and the third party repositories are key initiatives towards this goal. We also aim to extend the availability of apps in the main Fedora repositories wherever possible.

==== Platform integration

Software installed by default in Fedora Workstation should integrate with other platform components and adhere to the overall vision for Fedora Workstation. Software is expected to support Wayland and follow the GNOME Human Interface Guidelines. Exceptions to this should be rare.

==== Accessibility

From installing to using the Fedora Workstation, users with special needs shouldn’t be presented with any obstacles and have a pleasant experience.

==== Virtual machine and container experience

We aim to provide a first class experience for containers and virtual machines, including:

\&#42; Availability of container tools, including Podman, Skopeo, Buildah and OpenShift.
\&#42; High quality, easy to use, virtual machine tooling, through GNOME Boxes.
\&#42; High quality container development experience, including desktop integration for containers, and availability of OpenShift tooling and integrations (for example, the OpenShift VS Code plugin).

==== Encapsulation of development environments (Toolbx)

It should be possible to target deployment environments that are different from the operating system itself. An upgrade to a newer version of Fedora Workstation should not mean that a coding project needs to be modified to work with new versions of libraries and runtimes.

==== Support multimedia use cases

\&#42; Available applications to record and stream audio and video
\&#42; Support for AV equipment
\&#42; OS support for high dynamic range (primarily of interest to those doing image and video editing)
\&#42; Hardware acceleration for video encoding

==== Documentation

Users and administrators should be able to find information about how to use and manage their operating system on the system itself (offline through GNOME Help, manual pages and others) as well as on Fedora Project websites.


= Third-Party Repositories

////
Do not remove this page! It is linked to from apps in Fedora Workstation, including Software.

Goals for this page:

\&#42; describe what the 3rd party repos are
\&#42; explain how the 3rd party repos can be used
\&#42; list which repos and software are included
\&#42; assert Fedora's commitment to free and open source software, and list free/open alternatives
////

The Fedora Workstation Third Party repositories provide access to additional desktop software that is not included in Fedora's own repos. The repositories are selected and managed by the xref:index.adoc[Fedora Workstation Working Group], in accordance with https://docs.fedoraproject.org/en-US/fesco/Third_Party_Repository_Policy/[FESCo's third party repository policy].

The third-party repositories exist to provide access to additional software that may be necessary or important for users to have access to. This includes some proprietary software.

While facilitating the use of some proprietary software, the Fedora project continues to strongly believe in and promote https://www.gnu.org/philosophy/free-sw.en.html[free and open source software]. As a result, third party repositories must be enabled by the user in order to be used, and open source alternatives are recommended wherever possible.

== How to use

The following are basic instructions for how to use the third-party repositories.

=== Enabling third-party repositories

To install software from the third-party repositories, they must first be enabled. The easiest way to do this is in the Third-Party Repositories page of initial setup.

Alternative methods to enable the third-party repositories include:

\&#42; Through the dialog that is shown in the Software app when third-party repositories are not enabled.
\&#42; Enabling Third-Party Repositories in the Software app's Software Repository settings.

Note:
The repositories are preinstalled on every current Workstation, through the package \&#96;fedora-workstation-repositories\&#96;.

=== Installing from third-party repositories

Once the repos are enabled, the software they contain can be installed in the usual way. The repos can also be searched and installed using the \&#96;dnf\&#96; or \&#96;flatpak\&#96; commands, depending on the packaging format used.

=== Managing third-party repositories

The Software Repository settings in the Software app can be used to see which third-party repositories are enabled, or to enable and disable individual repositories.

== Included software

The following software is included in the third-party repositories:

[cols='1,1,1']
|===
|Repository|Includes|Availability

|\&#96;\&#96;flathub\&#96;\&#96; (filtered)
|Bitwarden, Discord, Microsoft Teams, Minecraft, Postman, Skype
|Fedora 35 – Fedora 37

|\&#96;\&#96;flathub\&#96;\&#96; (unfiltered)
|Everything from https://flathub.org/[flathub.org]
|≥ Fedora 38

|\&#96;\&#96;google-chrome\&#96;\&#96;
|Google Chrome
|≥ Fedora 25

|\&#96;\&#96;phracek-PyCharm\&#96;\&#96;
|PyCharm
|≥ Fedora 23

|\&#96;\&#96;rpmfusion-nonfree-nvidia-driver\&#96;\&#96;
|NVIDIA Graphics Driver
|≥ Fedora 28

|\&#96;\&#96;rpmfusion-nonfree-steam\&#96;\&#96;
|Steam
|≥ Fedora 28
|===


= Release Planning Schedule

The following is the template for the Workstation Working Group's release schedule. It follows the main Fedora release schedule, with additional check-in steps.

The schedule is meant to evolve as we use it, so please update this page as necessary.

[cols='1,3,5']
|===
|Week |Milestone| Tasks

|1
|Fedora development cycle begins
|

|20
|System-wide change proposal deadline
|

|21
|Self-contained change proposal deadline
|

|26
|GNOME beta target date \&amp; UI freeze
|1. check that all GNOME modules have releases, 2. update packages with the GNOME beta, 3. notify QA when the GNOME beta is available in Fedora, 4. plan a test week for when the beta will be available

|27
|Fedora branches from rawhide
|

|28
|GNOME test week happens around now
|

|30
|GNOME RC target date
|

|32
|Fedora beta release
|

|33
|GNOME stable target date
|1. update packages with the new GNOME release, 2. notify QA when the update is complete, 3. start preparing GNOME Fedora Flatpak updates

|35
|Fedora final freeze
|Start distributing GNOME Fedora Flatpak updates (should happen 2 weeks prior to expected release date)

|37
|Fedora stable release early target date
|Workstation publicity to be released with the new stable release: blog post, website updates, talks, etc
|===
