#!/usr/bin/env python3
"""
Cli for gen_rag.

File: gen_rag/ui/cli.py

Copyright 2025 Ankur Sinha
Author: Ankur Sinha <sanjay DOT ankur AT gmail DOT com>
"""

import asyncio
import subprocess
from contextlib import chdir
from pathlib import Path

import httpx
import typer
from neuroml_ai_utils.api import check_api_is_ready

rag_app = typer.Typer()


@rag_app.command()
def rag_cli(
    gui: bool = False,
    single_query: str = "",
):
    """NeuroML AI cli wrapper function"""
    print("*** NeuroML AI chat assistant ***")
    print("Please note that answers are generated by LLMs and may be incorrect.")
    print()
    print("Type 'quit' to exit.")
    print()
    print()

    url = "http://127.0.0.1:8005"

    if not gui:

        async def cli_main():
            """Cli main async"""
            from yaspin import yaspin

            # wait for API to be ready
            with yaspin(text="Waiting for API..."):
                response = await check_api_is_ready(f"{url}/health/ready")

            if len(single_query):
                print(f"NeuroML-AI (USER) >>> {single_query}\n\n")
                if single_query.lower() == "quit":
                    pass
                else:
                    with yaspin(text="Working ..."):
                        async with httpx.AsyncClient() as client:
                            response = await client.post(
                                f"{url}/query",
                                params={"query": single_query},
                                timeout=None,
                            )
                            response_result = response.json().get("result")
                            print(f"NeuroML-AI (AI) >>> {response_result}\n\n")

            else:
                while (query := input("NeuroML-AI (USER) >>> ")) != "quit":
                    # we use checkpoints, so we don't need to store and reload the
                    # state ourselves
                    with yaspin(text="Working ..."):
                        async with httpx.AsyncClient() as client:
                            response = await client.post(
                                f"{url}/query",
                                params={"query": query},
                                timeout=None,
                            )
                            response_result = response.json().get("result")
                            print(f"NeuroML-AI (AI) >>> {response_result}\n\n")

        try:
            asyncio.run(cli_main())
        except KeyboardInterrupt:
            print("\nInterrupted. Exiting.")

    else:
        # streamlit app
        cwd = Path(__file__).parent
        with chdir(cwd):
            subprocess.run("streamlit run streamlit_ui.py".split())

    print("NeuroML-AI >>> Bye!")


if __name__ == "__main__":
    rag_app()
